export const DOC_AUTH_SUCCESS='DOC_AUTH_SUCCESS';
export const DOC_AUTH_FAIL='DOC_AUTH_FAIL';
export const DOC_AUTH_LOGOUT='DOC_AUTH_LOGOUT';
export const DOC_AUTH_REDIRECT='DOC_AUTH_REDIRECT';
export const PAT_AUTH_SUCCESS='PAT_AUTH_SUCCESS';
export const PAT_AUTH_FAIL='PAT_AUTH_FAIL';
export const PAT_AUTH_LOGOUT='PAT_AUTH_LOGOUT';
export const PAT_AUTH_REDIRECT='PAT_AUTH_REDIRECT';

